#!/usr/bin/env python3
"""Embed data/*.json into data.js as JS globals the app loads directly.

Why this exists: opening index.html via file:// (double-click, no local
server) makes the browser block fetch() of local JSON files as a CORS
violation. Embedding the catalogs as plain JS avoids fetch entirely, so
the app works with a plain double-click.

Run after editing data/pectabs.json or data/sample-pectabs.json:
    python3 scripts/build-data-js.py
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent

SOURCES = [
    ("data/pectabs.json", "PECTAB_CATALOG"),
    ("data/sample-pectabs.json", "PECTAB_SAMPLE"),
]


def main():
    parts = [
        '"use strict";',
        "// Generated by scripts/build-data-js.py — do not edit by hand.",
        "// Edit data/*.json and re-run that script instead.",
        "",
    ]
    for rel_path, var_name in SOURCES:
        data = json.loads((ROOT / rel_path).read_text(encoding="utf-8"))
        parts.append(f"const {var_name} = {json.dumps(data, indent=2, ensure_ascii=False)};")
        parts.append("")

    (ROOT / "data.js").write_text("\n".join(parts), encoding="utf-8")
    print(f"wrote data.js ({sum(len(json.loads((ROOT / p).read_text())) for p, _ in SOURCES)} records total)")


if __name__ == "__main__":
    main()
